version: 1.0.{build}  
image: Visual Studio 2017

environment:  
  DOCKER_USER:
    secure: ock3hqsoE8czgST1KadYBQ==
  DOCKER_PASS:
    secure: /8p2IlbrRYnc01chpZ0TTyiq0MV+7AGUDewTP4PoKQk=

install:  
  - docker version

build_script:
    - dotnet clean
    - dotnet restore
    - dotnet publish containertest.csproj -c Release -r win10-x64
  
deploy_script: 
  - set REPO_API=richardcase/containertest-api_win
  - set VERSION=1.0.0
  - set TAG=latest
  - docker login -u="%DOCKER_USER%" -p="%DOCKER_PASS%"
  - docker build -f Dockerfile_win -t %REPO_API%:%APPVEYOR_REPO_COMMIT% --build-arg BUILD_DATE=%APPVEYOR_REPO_COMMIT%_TIMESTAMP --build-arg VCS_REF=%APPVEYOR_REPO_COMMIT% --build-arg VERSION=%VERSION% .
  - docker tag %REPO_API%:%APPVEYOR_REPO_COMMIT% %REPO_API%:%TAG%
  - docker tag %REPO_API%:%APPVEYOR_REPO_COMMIT% %REPO_API%:appv-%APPVEYOR_BUILD_NUMBER%
  - docker tag %REPO_API%:%APPVEYOR_REPO_COMMIT% %REPO_API%:%VERSION%
  - docker push %REPO_API%