FROM microsoft/dotnet:2.0.0-runtime-jessie

RUN mkdir /app
WORKDIR /app

COPY ./bin/Release/netcoreapp2.0/debian.8-x64/publish .

EXPOSE 5000

ENTRYPOINT ["/app/containertest"]

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
ARG VERSION
LABEL org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.name="API (Linux)" \
    org.label-schema.description="Web based API" \
    org.label-schema.url="https://github.com/richardcase/containertest" \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vcs-url="https://github.com/richardcase/containertest" \
    org.label-schema.vendor="Richard Case" \
    org.label-schema.version=$VERSION \
    org.label-schema.schema-version="1.0"