FROM microsoft/dotnet:2.0.0-runtime-nanoserver

RUN mkdir c:\\app
WORKDIR c:\\app

COPY ./bin/Release/netcoreapp2.0/win10-x64/publish .

EXPOSE 5000

ENTRYPOINT ["c:\\app\\containertest.exe"]

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
ARG VERSION
LABEL org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.name="API (Windows)" \
    org.label-schema.description="Web based API" \
    org.label-schema.url="https://github.com/richardcase/containertest" \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vcs-url="https://github.com/richardcase/containertest" \
    org.label-schema.vendor="Richard Case" \
    org.label-schema.version=$VERSION \
    org.label-schema.schema-version="1.0"